### ISSUE TITLE
Github action for edge releases doesn't trigger

### ISSUE THREAD

**Issue by jagedn** [nextflow-io/nf-nomad#69]
not sure why but it seems the `release` GH action is not fired 

I've tried to create an `-edge` version and a final `0.1.2` releases but it's not started by GH

**Comment by jagedn** [comment]
I've cloned the repo in my personal workspace and it works on it


https://github.com/jagedn/nf-nomad-tmp/actions

**Comment by abhi18av** [comment]
Maybe something to do with global settings here - let me try also 🤔

**Comment by abhi18av** [comment]
For me the latest tag `edge3` is showing up here https://github.com/nextflow-io/nf-nomad/releases/tag/0.1.2-edge3 from 12 hours ago 🤔 

I'll make an `edge4` now just to check

**Comment by jagedn** [comment]
It's a tag I created yesterday but the action didnt run (so no artifacts was attached)

**Comment by abhi18av** [comment]
Mm, strange - it's not triggering at all now. 

Should we test with a proper `0.1.2` release tag?

**Comment by jagedn** [comment]
I tested and didnt work

but If I clone the repo and tag in my repo the actions is executed ....

**Comment by abhi18av** [comment]
Mmm, then let's ask our colleagues for help on this one and we can focus on the dev and tests.


 @jhaezebr , @tomiles  @matthdsm - could you please help to troubleshoot this? 🙏

**Comment by jagedn** [comment]
maybe is a silly issue but ... can be because there are some commits with `[ci skip]`  ?

**Comment by abhi18av** [comment]
But, why would it work on your personal account then 🤔 


My hunch is more inclined towards the github secrets - but then it was working earlier just fine. 

Maybe, let's tweak the workflow to only work with `X.Y.Z` releases?

**Comment by abhi18av** [comment]
Some clues here https://github.com/orgs/community/discussions/27028

**Comment by tomiles** [comment]
Seems it was the regex that doesn't work on GitHub spliting it over 2 lines, does work to trigger a release on tag push for me.
```
name: release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-edge[0-9]+'
```

**Comment by jagedn** [comment]
I forked the repo and I was able to create an edge release 
see 

https://github.com/jagedn/nf-nomad-tmp/blob/master/.github/workflows/release.yml
https://github.com/jagedn/nf-nomad-tmp/releases/tag/0.1.4-edge1

also I simplified our repo to only one line and still doesnt work  :(

**Comment by jagedn** [comment]
well, not sure how I fixed but this is what I did:

I realized we had 2 releases pipelines completed using the tag `0.1.2` (I think we run them to validate the new edge nomenclature) but this tag was removed

Once deleted I was able to create a pre-release `0.1.2-edge3` and the action was executed and artifacts attached !!!!

https://github.com/nextflow-io/nf-nomad/releases/tag/0.1.2-edge3

**Comment by abhi18av** [comment]
Ah, this is curious! 

Changing the name of the issue for future reference.

**Comment by abhi18av** [comment]
Reopening this issue as it still persists in the release cycle.

=======


Also, adding a thought here to remove the difference between local CI/CD and `Github Action` (or other cloud CI/CD) to hear your thoughts on this topic 🙏 

The problem that we face (often enough) while working with remote systems is that we can't really test in local environments, be it the use-case of  

1. Cloud Batch systems vs a local-first (generalisable) batch system such as Kubernetes/Nomad system

2. Cloud build system vs a local-first (generalizable) build system such as Github Action.

The `nf-nomad` plugin, really aims to embrace the philosophy of generalizable-yet-simple systems. What could come next to help us build this tool better? 

For some time, I have been planning to explore such a tools called[ `Dapper`](https://dagger.io) which promises a simpler solution or CI/CD without the usual YAML debugging cycles ([refer here](https://docs.dagger.io/#what-problem-does-dagger-solve)). 


=======


What are your thoughts on this @jagedn , do you think it's worth exploring this at all? 



NOTE that I am aware of https://github.com/nektos/act, but it still doesn't really address the problem of YAML debugging.

**Comment by jagedn** [comment]
I'll close this issue as it seems is working now

- create a draft release (so new tag will be created)
- the pipeline is automagically executed
- when it ends artifacts will be attached to the release
